"""changed

Revision ID: 056349eeea28
Revises: 3f449ec002a8
Create Date: 2018-06-23 13:11:25.333010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056349eeea28'
down_revision = '3f449ec002a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchasers', sa.Column('shipping_address_line_1', sa.Text(), nullable=True))
    op.add_column('purchasers', sa.Column('shipping_city', sa.Text(), nullable=True))
    op.add_column('purchasers', sa.Column('shipping_country', sa.Text(), nullable=True))
    op.add_column('purchasers', sa.Column('shipping_country_code', sa.Text(), nullable=True))
    op.add_column('purchasers', sa.Column('shipping_name', sa.Text(), nullable=True))
    op.add_column('purchasers', sa.Column('shipping_state', sa.Text(), nullable=True))
    op.add_column('purchasers', sa.Column('shipping_zip', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchasers', 'shipping_zip')
    op.drop_column('purchasers', 'shipping_state')
    op.drop_column('purchasers', 'shipping_name')
    op.drop_column('purchasers', 'shipping_country_code')
    op.drop_column('purchasers', 'shipping_country')
    op.drop_column('purchasers', 'shipping_city')
    op.drop_column('purchasers', 'shipping_address_line_1')
    # ### end Alembic commands ###
