"""changed

Revision ID: 3f449ec002a8
Revises: e1ef91275c01
Create Date: 2018-06-23 13:05:26.518760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f449ec002a8'
down_revision = 'e1ef91275c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchasers', 'shipping_address_line_1')
    op.drop_column('purchasers', 'shipping_city')
    op.drop_column('purchasers', 'shipping_country')
    op.drop_column('purchasers', 'shipping_country_code')
    op.drop_column('purchasers', 'shipping_zip')
    op.drop_column('purchasers', 'shipping_state')
    op.drop_column('purchasers', 'shipping_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchasers', sa.Column('shipping_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('shipping_state', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('shipping_zip', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('shipping_country_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('shipping_country', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('shipping_city', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('shipping_address_line_1', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
