"""updated model

Revision ID: 64643b867df6
Revises: 
Create Date: 2018-06-12 15:32:13.587749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64643b867df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchasers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('tokenType', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('billing_name', sa.Text(), nullable=True),
    sa.Column('billing_country', sa.Text(), nullable=True),
    sa.Column('billing_country_code', sa.Text(), nullable=True),
    sa.Column('billing_zip', sa.Integer(), nullable=True),
    sa.Column('billing_address_line_1', sa.Text(), nullable=True),
    sa.Column('billing_city', sa.Text(), nullable=True),
    sa.Column('billing_state', sa.Text(), nullable=True),
    sa.Column('shipping_name', sa.Text(), nullable=True),
    sa.Column('shipping_country', sa.Text(), nullable=True),
    sa.Column('shipping_country_code', sa.Text(), nullable=True),
    sa.Column('shipping_zip', sa.Integer(), nullable=True),
    sa.Column('shipping_address_line_1', sa.Text(), nullable=True),
    sa.Column('shipping_city', sa.Text(), nullable=True),
    sa.Column('shipping_state', sa.Text(), nullable=True),
    sa.Column('price_paid', sa.Text(), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('has_shipped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchasers')
    # ### end Alembic commands ###
