"""changed

Revision ID: e7be714318ed
Revises: 056349eeea28
Create Date: 2018-06-23 13:14:00.609113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7be714318ed'
down_revision = '056349eeea28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchasers', 'has_shipped')
    op.drop_column('purchasers', 'order_quantity')
    op.drop_column('purchasers', 'price_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchasers', sa.Column('price_paid', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('order_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchasers', sa.Column('has_shipped', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
