"""changed

Revision ID: ffc96a258292
Revises: e7be714318ed
Create Date: 2018-06-23 13:14:23.442356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc96a258292'
down_revision = 'e7be714318ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchasers', sa.Column('has_shipped', sa.Boolean(), nullable=True))
    op.add_column('purchasers', sa.Column('order_quantity', sa.Integer(), nullable=True))
    op.add_column('purchasers', sa.Column('price_paid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchasers', 'price_paid')
    op.drop_column('purchasers', 'order_quantity')
    op.drop_column('purchasers', 'has_shipped')
    # ### end Alembic commands ###
